package domain.constants;

public enum LogicCoverageCriteriaId {
	
	COMPLETE_CLAUSE,
	RESTRICTED_ACTIVE_CLAUSE,
	RESTRICTED_INACTIVE_CLAUSE,
	CORRELATED_ACTIVE_CLAUSE,
	GENERAL_ACTIVE_CLAUSE,
	GENERAL_INACTIVE_CLAUSE,
	CLAUSE, 
	PREDICATE;

}
